/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invoice

import groovyjarjarpicocli.AutoComplete
import spock.lang.Specification

class AppTest extends Specification {

    def "test main"() {
        setup:
        def app = new AutoComplete.App()
        and:
        app.main()
    }

}
