package pl.futurecollars.invoice.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Invoice {

  @ApiModelProperty(value = "Invoice identification number (generated by application)", required = true, example = "1")
  private long id;

  @ApiModelProperty(value = "Invoice number (assigned by user)", required = true, example = "2022/10/12/00123")
  private String number;

  @ApiModelProperty(value = "Date invoice was created", required = true)
  private LocalDate date;

  @ApiModelProperty(value = "Company who is selling the product/service", required = true)
  private Company seller;

  @ApiModelProperty(value = "Company who bought the product/service", required = true)
  private Company buyer;

  @ApiModelProperty(value = "List of products/services", required = true)
  private List<InvoiceEntry> invoiceEntries;

}
